name: course_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Saly-10.png
    - assets/images/Saly-13.png
    - assets/images/Saly-20.png
    - assets/images/Saly-21.png
    - assets/images/Saly-24.png
    - assets/images/Saly-25.png
    - assets/images/Saly-36.png
    - assets/images/user(1).png
    - assets/images/user(2).png
    - assets/images/user(3).png
    - assets/images/user(4).png


